{{- if .Values.s3.credentials.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toil-wes-standalone.s3CredentialsSecretName" . }}
  labels:
    {{- include "toil-wes-standalone.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.s3.credentials.accessKeyKey }}: {{ .Values.s3.credentials.accessKeyValue | quote }}
  {{ .Values.s3.credentials.secretKeyKey }}: {{ .Values.s3.credentials.secretKeyValue | quote }}
{{- end }}
